### ISSUE TITLE
Game freezes due to Underground Biomes server stopping/closing

### ISSUE THREAD

**Issue by stealthusk** [LemADEC/UndergroundBiomesConstructs-Aang23#6]
It keeps saying the server is crashing with the mod on. It says this.

[14:01:15] [Server thread/INFO] [undergroundbiomes]: [UndergroundBiomes] Server Stopped

[14:01:15] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

It's so fricking annoying man. The game runs normally and then it freezes permanently. Idk what to do.
Also I got banned from your damn server for using all caps once. The hell man.

Here is the latest log: https://www.mediafire.com/file/9clhwjbkpob59rd/latest.log/file

**Comment by LemADEC** [comment]
That log is just saying that a server stop is requested, it happens way after your crash which is due to spiderstpo (Spiders 2.0). Given the long list of bugs in that mod, not fixed since 2 years, you're better off removing that mod altogether.
