### ISSUE TITLE
Default ores spawning instead of UBC variants

### ISSUE THREAD

**Issue by Jeanphavko** [LemADEC/UndergroundBiomesConstructs-Aang23#7]
Using the latest version: 1.12-1.3.14
This bug only concerns ores from other mods.

Demonstration video: https://user-images.githubusercontent.com/61831561/189525833-cd394444-ffbf-4fa9-b909-1559f92081a7.mp4
It is possible to convert the default ores to UBC variants by just right clicking on it.

Weird thing is that it occurs in random areas. 
![2022-07-16_17 13 06](https://user-images.githubusercontent.com/61831561/189525997-3f5d5734-ebbf-42dc-8735-895a369fc8c6.png)
Here, the pink ores are UBC variants and blue are default. There is a clear border between the two areas.

![2022-07-16_17 14 41](https://user-images.githubusercontent.com/61831561/189526199-befa12cd-ac96-4ea8-bc80-8ee614289f45.png)
And in this area the bug does not occur.

PS: this mod really is the BOP of caves! It adds so much diversity, I can't play without it now!!

**Comment by LemADEC** [comment]
Which other mods are involved here? try to reproduce with the least amount of mods, there's most probably one triggering the issue here.

**Comment by Jeanphavko** [comment]
Here is the full mods list.
![full](https://user-images.githubusercontent.com/61831561/190925048-2652ea52-d441-4f68-b433-997e2fc82f1f.png)

However, I reproduced the bug with only industrialcraft 2 and UBC.
![mini](https://user-images.githubusercontent.com/61831561/190925081-10aea182-4a36-4a9f-a13d-996b4271beb1.png)
I moved 150 blocks away from spawn on a new world and found a cluster of default IC2 ores:
![2022-09-18_21 10 21](https://user-images.githubusercontent.com/61831561/190925119-0f93baad-8765-4621-9ae7-f808b87db054.png)

GCLessOre and Silver n Salt are two mods I made with MCreator that add a few ores, and running them individually along with UBC also triggers the bug.

**Comment by LemADEC** [comment]
You can use the mod "CoFH World" for custom ore generation: you disable IC2 and your mods ore generations, add them through configuration in CoFH World. You can even add ThermalFoundation to have common ore textures and such if you like.

Ores need to be declared in UBC for them to be replaced.
You're using IC2Experimental while only IC2Classic is handled by default. You need to add your own configuration for IC2Experimental.
Same goes with your MCCreator mods: you need to declare those ores in the configuration for UBC to process them.

**Comment by Jeanphavko** [comment]
All ores are correctly configured in UBC.

I got the same bug while using cofh world generation:
![2022-10-01_20 43 30](https://user-images.githubusercontent.com/61831561/193423951-3030ae2d-05d3-4465-883e-e29bdc890592.png)
Blue blocks are default copper ore from ic2.

As this bug is rare, maybe there is a command to manually refresh the default ores in the loaded chunks, to simulate a right click on each ore? So the default ores will suddenly find out that they are supposed to be UBC variants?

**Comment by LemADEC** [comment]
I feel there's a bit of confusion here, so let me rewind a bit...
1- Regarding your video where an ore block changes when you right click it: this is just a client side refresh issue. You would only see it when exploring a freshly generated chunk which would never happen on a decent server were the map is pregenerated.
2- Ubification is already triggering upon ore placement by mods, whether it's done during generation or delayed for whatever reason.
3- Other mods may request to "redoOres" through the UBForceReProcessEvent event. Practically, I only known about COG using it on 1.7.10. There's no command to trigger it.
4- We can't prevent the game to unload or stop during the slight delay between ore placement and ubification, so if the server crash or unload the chunk too fast, all delayed ores in that chunk will be affected. There's no recovery mechanism for this case because it's a remote probability of happening and it's not so easy to implement.

**Comment by Jeanphavko** [comment]
Oh OK! So I just need to play on a server for the bug to not occur? Sorry for my poor understanding about this, I know basically nothing about programming x)
And regarding this issue in single player, you think it is solvable?

I'll try to set up a server then, I'll let you know what happens.

**Comment by Jeanphavko** [comment]
Hey! So I successfully set up a server and it worked! Using Chunk Pregenerator mod, all ores are 100% ubified inside the pregen area. (except when default minecraft stone spawns) 

But as soon as I exit the pregen area and start generating new chunks by moving my avatar in game, the bug occurs with an even higher frequency than what we've seen in singleplayer.
I've done a test with a 50 chunks square radius starting from 0/0/0, so the borders being approximately at 800 blocks from spawn.

Here what a border looks like:
![2022-10-10_20 53 51](https://user-images.githubusercontent.com/61831561/194955241-6ee8c187-bfb8-4a8a-a7e0-b215aff88df5.png)
Colored blocks as various default ores.

**Comment by LemADEC** [comment]
That only means your client is seeing the original ores. If you reload that area or go to the ores, there's a good chance they are actually ubified.

**Comment by Jeanphavko** [comment]
Damn!! OK I did not understand this was only visual! Indeed I just have to disconnect and reconnect to see the ubified ores. 
Thank you for your time and for maintaining this awesome mod!
